name: Build and Push Theia Lite Image

on:
  push:
    branches:
      - feat/theia-lite-old

jobs:
  build-and-push-lite:
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@v1.0.0
    with:
      docker-file: images/theia-lite/ToolDockerfile
      image-name: ghcr.io/ls1intum/theia/theia-lite
      docker-context: .
      tags: "pr-36"
      network: "host"
    secrets: inherit
